import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlayCircle } from "@fortawesome/free-solid-svg-icons";
import { faLinkedinIn, faInstagram } from "@fortawesome/free-brands-svg-icons";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fluxus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.topbg}>
        <div className={styles.heading}>FLUXUS'23</div>
        <div className={styles.text}>
          "Now is the winter of our discontent Made glorious summer by this sun
          <br />
          of York; An"
        </div>
        <div className={styles.socialicons}>
          <FontAwesomeIcon icon={faLinkedinIn} className={styles.socialicon} />
          <FontAwesomeIcon icon={faInstagram} className={styles.socialicon} />
        </div>
      </div>
      <div className={styles.bottombg}>
        <div className={styles.line}></div>
        <div className={styles.comingsoon}>COMING SOON</div>
        <div className={styles.text2}>
          Now is the winter of our discontent Made glorious summer by this sun
          of York; And all the clouds that lour'd upon our house In the Now is
          the winter of our discontent Made glorious summer by this sun of York;
          And all the clouds that lour'd upon our house In the{" "}
        </div>
        x
        <button className={styles.button}>
          Past Glimpses
          <FontAwesomeIcon icon={faPlayCircle} className={styles.playicon} />
        </button>
      </div>
    </div>
  );
}
